apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-dep
spec:
  selector:
    matchLabels:
      env: production

  replicas: 1
  template:
    metadata:
      labels:
        env: production

    spec:
      containers:
      - name: php-con
        image: mtabishk/webserver-apache-php:latest

        ports:
        - containerPort: 80
