apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  labels:
    env: production

spec:
  accessModes:
   - ReadWriteMany
  resources:  
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pvc
  labels:
    env: production

spec:
  accessModes:
   - ReadWriteMany
  resources:  
    requests:
      storage: 5Gi
